disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - missing_docs
  - force_unwrapping
  - explicit_type_interface
  - closure_spacing

excluded:
  - .build
  - build
  - DerivedData
  - Packages

line_length:
  warning: 120
  error: 150

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60

type_name:
  min_length: 3
  max_length: 50

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5
